issues:
  exclude-generated: disable

linters:
  enable:
    - errorlint
    - forbidigo
    - godot
    - gofmt
    - gofumpt
    - loggercheck
    - nilerr
    - perfsprint
    - revive
    - sloglint
    - stylecheck
    - unconvert
    - unused
    - whitespace
    - wrapcheck

linters-settings:
  wrapcheck:
    ignorePackageGlobs:
      - context
      - log/slog

      - github.com/jamestoyer/go-unifi-network-server/*
