skippedFiles:
  - "Account.json"
  - "AuthenticationRequest.json"
  - "BroadcastGroup.json"
  - "ChannelPlan.json"
  - "Dashboard.json"
  - "Device.json"
  - "DhcpOption.json"
  - "DpiApp.json"
  - "DpiGroup.json"
  - "DynamicDNS.json"
  - "FirewallGroup.json"
  - "FirewallRule.json"
  - "HeatMap.json"
  - "HeatMapPoint.json"
  - "Hotspot2Conf.json"
  - "HotspotOp.json"
  - "HotspotPackage.json"
  - "Map.json"
  - "MediaFile.json"
  - "NetworkConf.json"
  - "PortConf.json"
  - "PortForward.json"
  - "RadiusProfile.json"
  - "Routing.json"
  - "ScheduleTask.json"
  - "Setting.json"
  - "SpatialRecord.json"
  - "Tag.json"
  - "UserGroup.json"
  - "VirtualDevice.json"
  - "Wall.json"
  - "WlanConf.json"
  - "WlanGroup.json"
